ALTER TABLE image
    ADD COLUMN created_by VARCHAR(20);

ALTER TABLE image
    ADD COLUMN created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE image
    ADD COLUMN updated_by VARCHAR(20);
ALTER TABLE image
    ADD COLUMN updated_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP;


ALTER TABLE video
    ADD COLUMN created_by VARCHAR(20);

ALTER TABLE video
    ADD COLUMN created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE video
    ADD COLUMN updated_by VARCHAR(20);
ALTER TABLE video
    ADD COLUMN updated_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP;


